"""
agent/email_apply.py — Direct email application mode.

When Claude scores a job with apply_method == "email" and a contact_email is
known, this module:
  1. Reads the cover letter already written for the job.
  2. Composes a proper application email (cover letter as body, CV attached).
  3. Sends via Gmail SMTP.
  4. Updates the Google Sheet to 🟢 Applied.

The email subject and opening line are also generated by Claude so they're
tailored — not a generic "Please find attached my CV."
"""

import logging
import mimetypes
import pathlib
import smtplib
from datetime import date
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import anthropic

import config
from agent.retry import retry_anthropic
from agent.sheets import STATUS, update_status

logger = logging.getLogger(__name__)

CV_PDF_PATH = pathlib.Path(__file__).parent.parent / "data" / "cv.pdf"


# ---------------------------------------------------------------------------
# Claude: generate subject line
# ---------------------------------------------------------------------------

@retry_anthropic
def _generate_subject(cv: dict, job: dict) -> str:
    """Ask Claude for a sharp, specific subject line (not generic)."""
    client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
    prompt = (
        f"Write ONE email subject line for a job application.\n"
        f"Role: {job.get('title', '')}\n"
        f"Company: {job.get('company', '')}\n"
        f"Candidate: {cv.get('full_name', 'Zachary Devine')}\n\n"
        f"Rules:\n"
        f"- Max 12 words\n"
        f"- Must reference the specific role title\n"
        f"- Must not start with 'Application for' or 'Re:'\n"
        f"- Be direct and confident, not sycophantic\n"
        f"- Return ONLY the subject line text, nothing else"
    )
    resp = client.messages.create(
        model=config.CLAUDE_MODEL,
        max_tokens=60,
        messages=[{"role": "user", "content": prompt}],
    )
    return resp.content[0].text.strip().strip('"')


# ---------------------------------------------------------------------------
# Email composition
# ---------------------------------------------------------------------------

def _build_email(
    cv: dict,
    job: dict,
    cover_letter_text: str,
    subject: str,
    to_addr: str,
) -> MIMEMultipart:
    """Build the MIME email message."""
    from_addr = config.GMAIL_USER or cv.get("email", "")
    name = cv.get("full_name", "Zachary Devine")

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"]    = f"{name} <{from_addr}>"
    msg["To"]      = to_addr
    msg["Reply-To"] = cv.get("email", from_addr)

    # Plain-text body = cover letter + signature
    signature = (
        f"\n\n--\n{name}\n"
        f"{cv.get('phone', '')}\n"
        f"{cv.get('email', '')}\n"
        f"{cv.get('linkedin', '')}"
    )
    body = cover_letter_text + signature
    msg.attach(MIMEText(body, "plain", "utf-8"))

    # Attach CV PDF if it exists
    if CV_PDF_PATH.exists():
        safe_name = name.replace(" ", "_")
        with open(CV_PDF_PATH, "rb") as f:
            part = MIMEBase("application", "pdf")
            part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                "attachment",
                filename=f"{safe_name}_CV.pdf",
            )
            msg.attach(part)
        logger.info("CV PDF attached: %s", CV_PDF_PATH.name)
    else:
        logger.warning("CV PDF not found at %s — sending without attachment.", CV_PDF_PATH)

    return msg


def _send_email(msg: MIMEMultipart, to_addr: str) -> bool:
    """Send via Gmail SMTP with TLS."""
    smtp_user = config.GMAIL_USER
    smtp_pass = config.GMAIL_APP_PASSWORD

    if not smtp_user or not smtp_pass:
        logger.error("GMAIL_USER or GMAIL_APP_PASSWORD not set.")
        return False

    try:
        with smtplib.SMTP("smtp.gmail.com", 587, timeout=30) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, [to_addr], msg.as_string())
        logger.info("Application email sent to %s", to_addr)
        return True
    except smtplib.SMTPAuthenticationError:
        logger.error("SMTP auth failed — check GMAIL_USER / GMAIL_APP_PASSWORD.")
        return False
    except smtplib.SMTPException as exc:
        logger.error("SMTP error: %s", exc)
        return False
    except Exception as exc:
        logger.error("Unexpected error sending email: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def send_email_application(
    cv: dict,
    job: dict,
    cover_letter_path: str,
    sheet=None,
    dry_run: bool = False,
) -> bool:
    """
    Send a direct email application for *job*.

    Args:
        cv:                 Loaded cv.json.
        job:                Job dict with contact_email, title, company, url.
        cover_letter_path:  Path to the already-written cover letter .txt file.
        sheet:              Optional gspread worksheet for status updates.
        dry_run:            If True, compose but do not send.

    Returns:
        True on success (or dry_run), False on failure.
    """
    to_addr = job.get("contact_email", "").strip()
    if not to_addr:
        logger.warning("No contact email for %s — skipping email apply.", job.get("url"))
        return False

    # Read cover letter text
    cl_path = pathlib.Path(cover_letter_path)
    if not cl_path.exists():
        logger.error("Cover letter not found: %s", cover_letter_path)
        return False

    cover_letter_text = cl_path.read_text(encoding="utf-8").strip()

    # Generate subject line
    try:
        subject = _generate_subject(cv, job)
        logger.info("Email subject: %s", subject)
    except Exception as exc:
        logger.warning("Subject generation failed: %s — using fallback.", exc)
        subject = f"{job.get('title', 'Role')} — {cv.get('full_name', 'Application')}"

    # Build email
    msg = _build_email(cv, job, cover_letter_text, subject, to_addr)

    if dry_run:
        logger.info(
            "DRY RUN — email NOT sent.\n  To: %s\n  Subject: %s\n  Body preview: %.200s",
            to_addr, subject, cover_letter_text,
        )
        return True

    # Send
    success = _send_email(msg, to_addr)

    # Update sheet
    if success and sheet:
        update_status(
            sheet,
            job.get("url", ""),
            STATUS["applied"],
            extras={
                "date_applied": date.today().isoformat(),
                "contact_email": to_addr,
                "notes": f"Direct email to {to_addr}",
            },
        )

    return success


# ---------------------------------------------------------------------------
# Standalone test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import json, pathlib as _pl

    logging.basicConfig(level=logging.INFO)

    cv_path = _pl.Path(__file__).parent.parent / "data" / "cv.json"
    with open(cv_path) as f:
        cv = json.load(f)

    test_job = {
        "title": "Cyber Insurance Sales Executive",
        "company": "Acme Insurers",
        "url": "https://example.com/job/1",
        "contact_email": "careers@acme-example.com",
    }

    # Create a dummy cover letter
    dummy_cl = _pl.Path("/tmp/test_cover_letter.txt")
    dummy_cl.write_text(
        "This is a test cover letter body.\n\n"
        "It would normally be three strong paragraphs written by Claude."
    )

    send_email_application(cv, test_job, str(dummy_cl), dry_run=True)
