"""
agent/notify.py — Daily digest email via Gmail API or SMTP fallback.

Sends an HTML email to MY_EMAIL with:
- Table of today's found jobs (score, company, role, apply method)
- Attached cover letters for 🟡 jobs
- Attached screenshots for 🟠 queued jobs
- Link to the Google Sheet
"""

import logging
import mimetypes
import os
import pathlib
import smtplib
from datetime import date
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import config

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# HTML helpers
# ---------------------------------------------------------------------------

def _status_colour(status: str) -> str:
    colours = {
        "⚪": "#888888",
        "🔵": "#1a73e8",
        "🟡": "#f9ab00",
        "🟠": "#e37400",
        "🟢": "#34a853",
        "📬": "#8ab4f8",
        "❌": "#ea4335",
        "⭐": "#fbbc04",
        "⏭": "#aaaaaa",
    }
    for emoji, colour in colours.items():
        if emoji in status:
            return colour
    return "#000000"


def _build_html(jobs: list[dict]) -> str:
    today = date.today().strftime("%d %B %Y")
    n = len(jobs)

    rows = ""
    for j in jobs:
        status = j.get("Status", "")
        colour = _status_colour(status)
        url = j.get("Source URL", "#")
        company = j.get("Company", "")
        role = j.get("Role Title", "")
        score = j.get("Score", "")
        method = j.get("Apply Method", "")
        rows += (
            f"<tr>"
            f"<td><a href='{url}' style='color:#1a73e8'>{company}</a></td>"
            f"<td>{role}</td>"
            f"<td style='text-align:center'><strong>{score}</strong></td>"
            f"<td>{method}</td>"
            f"<td style='color:{colour}'>{status}</td>"
            f"</tr>\n"
        )

    sheet_url = (
        "https://docs.google.com/spreadsheets/d/search?q="
        + config.SHEET_NAME.replace(" ", "+")
    )

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; font-size: 14px; color: #333; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th {{ background: #1a73e8; color: #fff; padding: 8px 12px; text-align: left; }}
  td {{ padding: 7px 12px; border-bottom: 1px solid #e0e0e0; }}
  tr:nth-child(even) td {{ background: #f8f9fa; }}
  .footer {{ margin-top: 20px; font-size: 12px; color: #888; }}
</style>
</head>
<body>
<h2>Job Agent — {n} job{'s' if n != 1 else ''} today ({today})</h2>
<table>
  <thead>
    <tr>
      <th>Company</th><th>Role</th><th>Score</th><th>Apply Method</th><th>Status</th>
    </tr>
  </thead>
  <tbody>
{rows}
  </tbody>
</table>
<p class="footer">
  <a href="{sheet_url}">Open Google Sheet tracker →</a><br>
  Generated by job-agent
</p>
</body>
</html>"""


def _attach_file(msg: MIMEMultipart, filepath: str) -> None:
    """Attach a file to the MIME message."""
    path = pathlib.Path(filepath)
    if not path.exists():
        logger.warning("Attachment not found, skipping: %s", filepath)
        return
    mime_type, _ = mimetypes.guess_type(str(path))
    main_type, sub_type = (mime_type or "application/octet-stream").split("/", 1)
    with open(path, "rb") as f:
        attachment = MIMEBase(main_type, sub_type)
        attachment.set_payload(f.read())
        encoders.encode_base64(attachment)
        attachment.add_header(
            "Content-Disposition", "attachment", filename=path.name
        )
        msg.attach(attachment)
    logger.info("Attached: %s", path.name)


def send_daily_digest(jobs: list[dict], dry_run: bool = False) -> bool:
    """
    Send the HTML digest email.

    Args:
        jobs:    List of job row dicts (from sheets.get_todays_jobs).
        dry_run: If True, build the email but do not send it.

    Returns:
        True on success (or dry_run), False on failure.
    """
    if not jobs:
        logger.info("No jobs to digest today — skipping email.")
        return True

    to_addr = config.MY_EMAIL
    if not to_addr:
        logger.error("MY_EMAIL is not set — cannot send digest.")
        return False

    today = date.today().strftime("%d %b %Y")
    n = len(jobs)
    subject = f"Job Agent — {n} job{'s' if n != 1 else ''} ready today ({today})"

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"] = config.GMAIL_USER or to_addr
    msg["To"] = to_addr

    html_part = MIMEText(_build_html(jobs), "html", "utf-8")
    msg.attach(html_part)

    # Attach cover letters for 🟡 jobs
    for job in jobs:
        if "🟡" in job.get("Status", ""):
            cl_path = job.get("Cover Letter Path", "")
            if cl_path:
                _attach_file(msg, cl_path)

    # Attach screenshots for 🟠 queued jobs
    for job in jobs:
        if "🟠" in job.get("Status", ""):
            notes = job.get("Notes", "")
            if notes.startswith("Screenshot: "):
                sc_path = notes.replace("Screenshot: ", "").strip()
                _attach_file(msg, sc_path)

    if dry_run:
        logger.info("DRY RUN — email NOT sent. Subject: %s", subject)
        logger.info("Would email %d jobs to %s", n, to_addr)
        return True

    return _send_via_smtp(msg, to_addr)


def _send_via_smtp(msg: MIMEMultipart, to_addr: str) -> bool:
    """Send *msg* using Gmail SMTP (TLS on port 587)."""
    smtp_user = config.GMAIL_USER
    smtp_pass = config.GMAIL_APP_PASSWORD

    if not smtp_user or not smtp_pass:
        logger.error("GMAIL_USER or GMAIL_APP_PASSWORD not set — cannot send email.")
        return False

    try:
        with smtplib.SMTP("smtp.gmail.com", 587, timeout=30) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, [to_addr], msg.as_string())
        logger.info("Digest email sent to %s", to_addr)
        return True
    except smtplib.SMTPAuthenticationError:
        logger.error(
            "SMTP authentication failed — check GMAIL_USER and GMAIL_APP_PASSWORD."
        )
    except smtplib.SMTPException as exc:
        logger.error("SMTP error sending digest: %s", exc)
    except Exception as exc:
        logger.error("Unexpected error sending digest: %s", exc)
    return False


# ---------------------------------------------------------------------------
# Standalone test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    sample_jobs = [
        {
            "Company": "Acme Insurers",
            "Role Title": "Cyber Insurance Sales Executive",
            "Source URL": "https://example.com/job/1",
            "Score": 9,
            "Apply Method": "email",
            "Status": "🟡 Cover Letter Written",
            "Cover Letter Path": "",
            "Notes": "",
        },
        {
            "Company": "Cyber Brokers Ltd",
            "Role Title": "BDM InsurTech",
            "Source URL": "https://example.com/job/2",
            "Score": 8,
            "Apply Method": "portal",
            "Status": "🟠 Queued",
            "Cover Letter Path": "",
            "Notes": "",
        },
    ]

    send_daily_digest(sample_jobs, dry_run=True)
